services:
  - type: web
    name: brochure-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: WEB_APP_URL
        sync: false
      - key: PORT
        value: 8000

